### ISSUE TITLE
能说明下生成的代码如何使用吗？

### ISSUE THREAD

**Issue by fmy1993** [Acorn2/mybatisgenerator#2]

**Comment by fmy1993** [comment]
![image](https://user-images.githubusercontent.com/12120788/125157509-08950b80-e19e-11eb-9af5-8746741c7c6c.png)
![image](https://user-images.githubusercontent.com/12120788/125157529-1cd90880-e19e-11eb-818a-f243dfda6bf0.png)
保留了common和util包，使用生成代码，但是报错找不到mapper，其实明明是有mapper文件的

**Comment by Acorn2** [comment]
service实现类中没用到注解吗？



在 2021-07-10 16:46:08，"fmy1993" ***@***.***> 写道：



保留了common和util包，使用生成代码，但是报错找不到mapper，其实明明是有mapper文件的
