### ISSUE TITLE
生成的dto中没有listdto

### ISSUE THREAD

**Issue by fmy1993** [Acorn2/mybatisgenerator#3]
![image](https://user-images.githubusercontent.com/12120788/125158757-cb347c00-e1a5-11eb-89d5-4ecc7e449faa.png)

**Comment by Acorn2** [comment]
这个类暂时不要了，目前只保留了分页查询实体类和新增更新实体类，我去检查一下代码，去掉不必要的信息



在 2021-07-10 17:40:10，"fmy1993" ***@***.***> 写道：

**Comment by Acorn2** [comment]
另外你这个服务实现类中怎么会引用ListDTO，我自己刚才自己重试了一遍，不会生成这个import语句
